"""empty message

Revision ID: 47a2db38d36f
Revises: dad4f662a9ff
Create Date: 2020-10-21 18:59:37.296323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a2db38d36f'
down_revision = 'dad4f662a9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts_categories',
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
