"""empty message

Revision ID: 950fe70a39fc
Revises: 4b92a42d7d2b
Create Date: 2020-10-21 20:57:11.811178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950fe70a39fc'
down_revision = '4b92a42d7d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
